import "./globals.css";
import "primereact/resources/themes/saga-blue/theme.css";
import "primereact/resources/primereact.min.css";
import "primeicons/primeicons.css";
import "primeflex/primeflex.css";
import { Montserrat } from "next/font/google";
import Navbar from "./components/navbar/page";
import Footer from "./components/footer/page";
import SmoothScroll from "./SmoothScroll/page";

const montserrat = Montserrat({
  weight: ["400", "700"],
  variable: "--font-montserrat",
});

export const metadata = {
  title: "MonoLens",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <SmoothScroll>
          <section className="bg-[#040a0a]  text-white" >
          <Navbar></Navbar>
          <main>{children}</main>
          <Footer></Footer>
        </section>
        </SmoothScroll>
      </body>
    </html>
  );
}
